dist: trusty
language: cpp
sudo: false

addons:
  apt:
    sources:
      - deadsnakes  # python3.6
      - ubuntu-toolchain-r-test  # gcc
      - llvm-toolchain-trusty-5.0 # clang-5.0
    packages:
      - python3.6
      - python3.6-dev
      - gcc-7
      - g++-7
      - clang-5.0

env:
  global:
    - HOME_PREFIX="$HOME/prefix"
    - LD_LIBRARY_PATH="$HOME_PREFIX/lib"
    # Boost
    - BOOST_ROOT="$HOME_PREFIX"
    - BOOST_INCLUDEDIR="$HOME_PREFIX/include"
    - BOOST_LIBRARYDIR="$HOME_PREFIX/lib"
    # Python
    - PYTHONPATH="$HOME_PREFIX/lib/python3.6"
  - MATRIX_EVAL="CC=gcc-7 CXX=g++-7"
  - MATRIX_EVAL="CC=clang-5.0 CXX=clang++-5.0"

before_install:
  - eval "$MATRIX_EVAL"
  - $CC --version
  - $CXX --version
  # Sanity check before long compilation
  - $CXX -std=c++17 ./ci/travis/cpp/cpp17.cpp -o cpp17
  - ./cpp17

install: ./ci/travis/install.sh

script: ./ci/travis/test.sh
