dist: trusty
language: generic
sudo: false

addons:
  apt:
    sources:
      - deadsnakes  # python3.6
      - ubuntu-toolchain-r-test  # gcc
      - llvm-toolchain-trusty-5.0 # clang-5.0
    packages:
      - python3.6
      - python3.6-dev
      - gcc-7
      - g++-7
      - clang-5.0
      # gRPC
      - openssl
      - libssl-dev

cache:
  directories:
    - $HOME/prefix

env:
  - MATRIX_EVAL="export BUILD=meson CC=gcc-7 CXX=g++-7"
  - MATRIX_EVAL="export BUILD=meson CC=clang-5.0 CXX=clang++-5.0"
  - MATRIX_EVAL="export BUILD=cmake-make CC=gcc-7 CXX=g++-7"
  - MATRIX_EVAL="export BUILD=cmake-make CC=clang-5.0 CXX=clang++-5.0"
  - MATRIX_EVAL="export BUILD=cmake-ninja CC=gcc-7 CXX=g++-7"
  - MATRIX_EVAL="export BUILD=cmake-ninja CC=clang-5.0 CXX=clang++-5.0"

before_install:
  # General overrides
  - export JOBS=3
  - export HOME_PREFIX="$HOME/prefix"
  - export HOME_TMP_PREFIX="$HOME/temp_prefix"
  - export PATH="$HOME_TMP_PREFIX/bin:$HOME_PREFIX/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME_PREFIX/lib:$LD_LIBRARY_PATH"
  - export LD_LIBRARY_PATH="$HOME_TMP_PREFIX/lib:$LD_LIBRARY_PATH"
  - export PKG_CONFIG_PATH="$HOME_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  - export PKG_CONFIG_PATH="$HOME_TMP_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  # Boost
  - export BOOST_ROOT="$HOME_PREFIX"
  - export BOOST_INCLUDEDIR="$HOME_PREFIX/include"
  - export BOOST_LIBRARYDIR="$HOME_PREFIX/lib"
  # Python
  - export PYTHON3="/usr/bin/python3.6"
  - export PYTHONPATH="$HOME_PREFIX/lib/python3.6/site-packages:$PYTHONPATH"
  - export PYTHONPATH="$HOME_TMP_PREFIX/lib/python3.6/site-packages:$PYTHONPATH"
  # Build version
  - eval "$MATRIX_EVAL"
  - $CC --version
  - $CXX --version
  # Sanity check before long compilation
  - $CXX -std=c++17 ./ci/travis/cpp/cpp17.cpp -o cpp17
  - ./cpp17

install: ./ci/travis/install.sh

script: ./ci/travis/test.sh
