dist: trusty
language: generic
sudo: false

addons:
  apt:
    sources:
      - deadsnakes  # python3.6
      - ubuntu-toolchain-r-test  # gcc
      - llvm-toolchain-trusty-5.0 # clang-5.0
    packages:
      - python3.6
      - python3.6-dev
      - gcc-7
      - g++-7
      - clang-5.0

cache:
  directories:
    - $HOME/prefix

env:
  - MATRIX_EVAL="export CC=gcc-7 CXX=g++-7"
  - MATRIX_EVAL="export CC=clang-5.0 CXX=clang++-5.0"

before_install:
  # General overrides
  - export HOME_PREFIX="$HOME/prefix"
  - export PATH="$HOME_PREFIX/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME_PREFIX/lib"
  - export PKG_CONFIG_PATH="$HOME_PREFIX/lib/pkgconfig"
  # Boost
  - export BOOST_ROOT="$HOME_PREFIX"
  - export BOOST_INCLUDEDIR="$HOME_PREFIX/include"
  - export BOOST_LIBRARYDIR="$HOME_PREFIX/lib"
  # Python
  - export PYTHONPATH="$HOME_PREFIX/lib/python3.6/site-packages"
  # Build version
  - eval "$MATRIX_EVAL"
  - $CC --version
  - $CXX --version
  # Sanity check before long compilation
  - $CXX -std=c++17 ./ci/travis/cpp/cpp17.cpp -o cpp17
  - ./cpp17

install: ./ci/travis/install.sh

script: ./ci/travis/test.sh
