// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bacs/process/resource.proto

/*
Package process is a generated protocol buffer package.

It is generated from these files:
	bacs/process/resource.proto
	bacs/process/source.proto

It has these top-level messages:
	ResourceLimits
	ResourceUsage
	Source
	Buildable
	BuildSettings
	BuilderConfig
	BuildResult
	ExecutionResult
*/
package process

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceLimits struct {
	TimeLimitMillis     uint64 `protobuf:"varint,1,opt,name=time_limit_millis,json=timeLimitMillis" json:"time_limit_millis,omitempty"`
	MemoryLimitBytes    uint64 `protobuf:"varint,2,opt,name=memory_limit_bytes,json=memoryLimitBytes" json:"memory_limit_bytes,omitempty"`
	OutputLimitBytes    uint64 `protobuf:"varint,3,opt,name=output_limit_bytes,json=outputLimitBytes" json:"output_limit_bytes,omitempty"`
	NumberOfProcesses   uint64 `protobuf:"varint,4,opt,name=number_of_processes,json=numberOfProcesses" json:"number_of_processes,omitempty"`
	RealTimeLimitMillis uint64 `protobuf:"varint,5,opt,name=real_time_limit_millis,json=realTimeLimitMillis" json:"real_time_limit_millis,omitempty"`
}

func (m *ResourceLimits) Reset()                    { *m = ResourceLimits{} }
func (m *ResourceLimits) String() string            { return proto.CompactTextString(m) }
func (*ResourceLimits) ProtoMessage()               {}
func (*ResourceLimits) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResourceLimits) GetTimeLimitMillis() uint64 {
	if m != nil {
		return m.TimeLimitMillis
	}
	return 0
}

func (m *ResourceLimits) GetMemoryLimitBytes() uint64 {
	if m != nil {
		return m.MemoryLimitBytes
	}
	return 0
}

func (m *ResourceLimits) GetOutputLimitBytes() uint64 {
	if m != nil {
		return m.OutputLimitBytes
	}
	return 0
}

func (m *ResourceLimits) GetNumberOfProcesses() uint64 {
	if m != nil {
		return m.NumberOfProcesses
	}
	return 0
}

func (m *ResourceLimits) GetRealTimeLimitMillis() uint64 {
	if m != nil {
		return m.RealTimeLimitMillis
	}
	return 0
}

type ResourceUsage struct {
	// TODO: do we need to export Process::ResourceUsage::timeUsage?
	TimeUsageMillis  uint64 `protobuf:"varint,1,opt,name=time_usage_millis,json=timeUsageMillis" json:"time_usage_millis,omitempty"`
	MemoryUsageBytes uint64 `protobuf:"varint,2,opt,name=memory_usage_bytes,json=memoryUsageBytes" json:"memory_usage_bytes,omitempty"`
}

func (m *ResourceUsage) Reset()                    { *m = ResourceUsage{} }
func (m *ResourceUsage) String() string            { return proto.CompactTextString(m) }
func (*ResourceUsage) ProtoMessage()               {}
func (*ResourceUsage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResourceUsage) GetTimeUsageMillis() uint64 {
	if m != nil {
		return m.TimeUsageMillis
	}
	return 0
}

func (m *ResourceUsage) GetMemoryUsageBytes() uint64 {
	if m != nil {
		return m.MemoryUsageBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*ResourceLimits)(nil), "bacs.process.ResourceLimits")
	proto.RegisterType((*ResourceUsage)(nil), "bacs.process.ResourceUsage")
}

func init() { proto.RegisterFile("bacs/process/resource.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x40, 0xa9, 0xae, 0x8a, 0xc1, 0xaf, 0xcd, 0x82, 0x14, 0xbc, 0xc8, 0x9e, 0x44, 0xa4, 0x7b,
	0xd8, 0x7f, 0xb0, 0x67, 0x45, 0x29, 0x7a, 0xf1, 0x12, 0x9a, 0x32, 0x95, 0x40, 0x62, 0x4a, 0x26,
	0x39, 0xf4, 0xc7, 0x0b, 0x92, 0x49, 0x2a, 0x96, 0xf6, 0x38, 0xf3, 0x5e, 0x60, 0x1e, 0x61, 0x77,
	0xb2, 0x69, 0x71, 0xd7, 0x3b, 0xdb, 0x02, 0xe2, 0xce, 0x01, 0xda, 0xe0, 0x5a, 0xa8, 0x7a, 0x67,
	0xbd, 0xe5, 0x17, 0x11, 0x56, 0x19, 0x6e, 0x7f, 0x0a, 0x76, 0x55, 0x67, 0xe1, 0x59, 0x19, 0xe5,
	0x91, 0x3f, 0xb2, 0xb5, 0x57, 0x06, 0x84, 0x8e, 0xa3, 0x30, 0x4a, 0x6b, 0x85, 0x65, 0x71, 0x5f,
	0x3c, 0xac, 0xea, 0xeb, 0x08, 0x48, 0x7b, 0xa1, 0x35, 0x7f, 0x62, 0xdc, 0x80, 0xb1, 0x6e, 0xc8,
	0xb6, 0x1c, 0x3c, 0x60, 0x79, 0x44, 0xf2, 0x4d, 0x22, 0xa4, 0x1f, 0xe2, 0x3e, 0xda, 0x36, 0xf8,
	0x3e, 0xf8, 0x89, 0x7d, 0x9c, 0xec, 0x44, 0xfe, 0xd9, 0x15, 0xdb, 0x7c, 0x07, 0x23, 0xc1, 0x09,
	0xdb, 0x89, 0x7c, 0x2f, 0x60, 0xb9, 0x22, 0x7d, 0x9d, 0xd0, 0x6b, 0xf7, 0x36, 0x02, 0xbe, 0x67,
	0xb7, 0x0e, 0x1a, 0x2d, 0xe6, 0xc7, 0x9f, 0xd0, 0x93, 0x4d, 0xa4, 0xef, 0xd3, 0x80, 0xad, 0x62,
	0x97, 0x63, 0xfe, 0x07, 0x36, 0x5f, 0xf0, 0x57, 0x1f, 0xe2, 0xb4, 0x50, 0x4f, 0xd6, 0xac, 0x3e,
	0xd9, 0x0b, 0xf5, 0xa4, 0x53, 0xcf, 0xe1, 0xfc, 0xf3, 0x2c, 0x57, 0xc8, 0x53, 0xfa, 0x8a, 0xfd,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x4c, 0xde, 0x97, 0xa9, 0x01, 0x00, 0x00,
}
