// Code generated by protoc-gen-go.
// source: bunsan/broker/connection.proto
// DO NOT EDIT!

/*
Package broker is a generated protocol buffer package.

It is generated from these files:
	bunsan/broker/connection.proto
	bunsan/broker/protocol.proto

It has these top-level messages:
	Credentials
	ConnectionParameters
	Constraints
	Task
	Status
	Result
*/
package broker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Credentials struct {
	Method      string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password    string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Certificate []byte `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Key         []byte `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}

type ConnectionParameters struct {
	// required
	Identifier  string       `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Credentials *Credentials `protobuf:"bytes,2,opt,name=credentials" json:"credentials,omitempty"`
	Host        string       `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port        int32        `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	VirtualHost string       `protobuf:"bytes,5,opt,name=virtual_host" json:"virtual_host,omitempty"`
}

func (m *ConnectionParameters) Reset()         { *m = ConnectionParameters{} }
func (m *ConnectionParameters) String() string { return proto.CompactTextString(m) }
func (*ConnectionParameters) ProtoMessage()    {}

func (m *ConnectionParameters) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type Constraints struct {
	Resource []string `protobuf:"bytes,1,rep,name=resource" json:"resource,omitempty"`
}

func (m *Constraints) Reset()         { *m = Constraints{} }
func (m *Constraints) String() string { return proto.CompactTextString(m) }
func (*Constraints) ProtoMessage()    {}
