// Code generated by protoc-gen-go.
// source: bacs/file/path.proto
// DO NOT EDIT!

/*
Package file is a generated protocol buffer package.

It is generated from these files:
	bacs/file/path.proto
	bacs/file/range.proto

It has these top-level messages:
	Path
	Range
*/
package file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// / Filesystem path.
type Path struct {
	// / If specified, path is absolute, otherwise -- relative.
	Root string `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	// / Path elements, will be concatenated using OS-specific delimiter.
	Element []string `protobuf:"bytes,2,rep,name=element" json:"element,omitempty"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
