// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bacs/utility/archiver.proto

/*
Package utility is a generated protocol buffer package.

It is generated from these files:
	bacs/utility/archiver.proto

It has these top-level messages:
	Archiver
*/
package utility

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Archiver struct {
	// required
	Type   string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
}

func (m *Archiver) Reset()                    { *m = Archiver{} }
func (m *Archiver) String() string            { return proto.CompactTextString(m) }
func (*Archiver) ProtoMessage()               {}
func (*Archiver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Archiver) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Archiver) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func init() {
	proto.RegisterType((*Archiver)(nil), "bacs.utility.Archiver")
}

func init() { proto.RegisterFile("bacs/utility/archiver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x4a, 0x4c, 0x2e,
	0xd6, 0x2f, 0x2d, 0xc9, 0xcc, 0xc9, 0x2c, 0xa9, 0xd4, 0x4f, 0x2c, 0x4a, 0xce, 0xc8, 0x2c, 0x4b,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0x49, 0xea, 0x41, 0x25, 0x95, 0xcc,
	0xb8, 0x38, 0x1c, 0xa1, 0xf2, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x5a, 0x7e, 0x51, 0x6e, 0x62, 0x89,
	0x04, 0x13, 0x58, 0x14, 0xca, 0x73, 0xe2, 0x8c, 0x62, 0x87, 0x1a, 0x91, 0xc4, 0x06, 0x36, 0xd7,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xd6, 0xdd, 0xed, 0x76, 0x00, 0x00, 0x00,
}
