// Code generated by protoc-gen-go.
// source: bacs/utility/archiver.proto
// DO NOT EDIT!

/*
Package bacs_utility is a generated protocol buffer package.

It is generated from these files:
	bacs/utility/archiver.proto

It has these top-level messages:
	Archiver
*/
package bacs_utility

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Archiver struct {
	// required
	Type   string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
}

func (m *Archiver) Reset()         { *m = Archiver{} }
func (m *Archiver) String() string { return proto.CompactTextString(m) }
func (*Archiver) ProtoMessage()    {}
