// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bacs/file/path.proto

/*
Package file is a generated protocol buffer package.

It is generated from these files:
	bacs/file/path.proto
	bacs/file/range.proto

It has these top-level messages:
	Path
	Range
*/
package file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Filesystem path.
type Path struct {
	// / If specified, path is absolute, otherwise -- relative.
	Root string `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	// / Path elements, will be concatenated using OS-specific delimiter.
	Element []string `protobuf:"bytes,2,rep,name=element" json:"element,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Path) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *Path) GetElement() []string {
	if m != nil {
		return m.Element
	}
	return nil
}

func init() {
	proto.RegisterType((*Path)(nil), "bacs.file.Path")
}

func init() { proto.RegisterFile("bacs/file/path.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x4a, 0x4c, 0x2e,
	0xd6, 0x4f, 0xcb, 0xcc, 0x49, 0xd5, 0x2f, 0x48, 0x2c, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x04, 0x89, 0xea, 0x81, 0x44, 0x95, 0x4c, 0xb8, 0x58, 0x02, 0x12, 0x4b, 0x32, 0x84,
	0x84, 0xb8, 0x58, 0x8a, 0xf2, 0xf3, 0x4b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c,
	0x21, 0x09, 0x2e, 0xf6, 0xd4, 0x9c, 0xd4, 0xdc, 0xd4, 0xbc, 0x12, 0x09, 0x26, 0x05, 0x66, 0x0d,
	0xce, 0x20, 0x18, 0xd7, 0x89, 0x2d, 0x8a, 0x05, 0xa4, 0x3b, 0x89, 0x0d, 0x6c, 0x9e, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x46, 0x33, 0x38, 0xe2, 0x67, 0x00, 0x00, 0x00,
}
