// Code generated by protoc-gen-go.
// source: bacs/archive/problem/error.proto
// DO NOT EDIT!

/*
Package bacs_archive_problem is a generated protocol buffer package.

It is generated from these files:
	bacs/archive/problem/error.proto
	bacs/archive/problem/flag.proto
	bacs/archive/problem/id.proto
	bacs/archive/problem/import.proto
	bacs/archive/problem/status.proto

It has these top-level messages:
	Error
*/
package bacs_archive_problem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Error_Code int32

const (
	Error_UNKNOWN        Error_Code = 0
	Error_NOT_FOUND      Error_Code = 1
	Error_LOCKED         Error_Code = 2
	Error_READ_ONLY      Error_Code = 3
	Error_PENDING_IMPORT Error_Code = 4
	Error_INVALID_FORMAT Error_Code = 5
)

var Error_Code_name = map[int32]string{
	0: "UNKNOWN",
	1: "NOT_FOUND",
	2: "LOCKED",
	3: "READ_ONLY",
	4: "PENDING_IMPORT",
	5: "INVALID_FORMAT",
}
var Error_Code_value = map[string]int32{
	"UNKNOWN":        0,
	"NOT_FOUND":      1,
	"LOCKED":         2,
	"READ_ONLY":      3,
	"PENDING_IMPORT": 4,
	"INVALID_FORMAT": 5,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}

type Error struct {
	Code   Error_Code `protobuf:"varint,1,opt,name=code,enum=bacs.archive.problem.Error_Code" json:"code,omitempty"`
	Reason string     `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("bacs.archive.problem.Error_Code", Error_Code_name, Error_Code_value)
}
