// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bunsan/broker/rabbit/connection.proto

/*
Package rabbit is a generated protocol buffer package.

It is generated from these files:
	bunsan/broker/rabbit/connection.proto

It has these top-level messages:
	RabbitTask
	RabbitStatus
	RabbitResult
*/
package rabbit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bunsan_broker "bunsan/broker"
import bunsan_broker1 "bunsan/broker"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RabbitTask struct {
	Identifier  string                     `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Task        *bunsan_broker1.Task       `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
	Constraints *bunsan_broker.Constraints `protobuf:"bytes,3,opt,name=constraints" json:"constraints,omitempty"`
	StatusQueue string                     `protobuf:"bytes,4,opt,name=status_queue,json=statusQueue" json:"status_queue,omitempty"`
	ResultQueue string                     `protobuf:"bytes,5,opt,name=result_queue,json=resultQueue" json:"result_queue,omitempty"`
	ErrorQueue  string                     `protobuf:"bytes,6,opt,name=error_queue,json=errorQueue" json:"error_queue,omitempty"`
}

func (m *RabbitTask) Reset()                    { *m = RabbitTask{} }
func (m *RabbitTask) String() string            { return proto.CompactTextString(m) }
func (*RabbitTask) ProtoMessage()               {}
func (*RabbitTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RabbitTask) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *RabbitTask) GetTask() *bunsan_broker1.Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *RabbitTask) GetConstraints() *bunsan_broker.Constraints {
	if m != nil {
		return m.Constraints
	}
	return nil
}

func (m *RabbitTask) GetStatusQueue() string {
	if m != nil {
		return m.StatusQueue
	}
	return ""
}

func (m *RabbitTask) GetResultQueue() string {
	if m != nil {
		return m.ResultQueue
	}
	return ""
}

func (m *RabbitTask) GetErrorQueue() string {
	if m != nil {
		return m.ErrorQueue
	}
	return ""
}

type RabbitStatus struct {
	Identifier string                 `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Status     *bunsan_broker1.Status `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *RabbitStatus) Reset()                    { *m = RabbitStatus{} }
func (m *RabbitStatus) String() string            { return proto.CompactTextString(m) }
func (*RabbitStatus) ProtoMessage()               {}
func (*RabbitStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RabbitStatus) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *RabbitStatus) GetStatus() *bunsan_broker1.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type RabbitResult struct {
	Identifier string                 `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Result     *bunsan_broker1.Result `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *RabbitResult) Reset()                    { *m = RabbitResult{} }
func (m *RabbitResult) String() string            { return proto.CompactTextString(m) }
func (*RabbitResult) ProtoMessage()               {}
func (*RabbitResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RabbitResult) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *RabbitResult) GetResult() *bunsan_broker1.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*RabbitTask)(nil), "bunsan.broker.rabbit.RabbitTask")
	proto.RegisterType((*RabbitStatus)(nil), "bunsan.broker.rabbit.RabbitStatus")
	proto.RegisterType((*RabbitResult)(nil), "bunsan.broker.rabbit.RabbitResult")
}

func init() { proto.RegisterFile("bunsan/broker/rabbit/connection.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xd6, 0xa0, 0x93, 0x9e, 0xa2, 0x42, 0x08, 0x52, 0x6b, 0x41, 0xec, 0xc5, 0x04,
	0xf4, 0xea, 0x49, 0x7f, 0x81, 0xab, 0x27, 0x41, 0x64, 0x13, 0x57, 0x58, 0x52, 0x76, 0x75, 0x76,
	0xf2, 0xe7, 0x3d, 0x49, 0x66, 0x16, 0xda, 0x04, 0x44, 0xaf, 0x6f, 0xbf, 0xf9, 0x78, 0x8f, 0x04,
	0x2e, 0x9b, 0xde, 0x05, 0xed, 0xea, 0x06, 0x7d, 0x67, 0xb0, 0x46, 0xdd, 0x34, 0x96, 0xea, 0xd6,
	0x3b, 0x67, 0x5a, 0xb2, 0xde, 0x55, 0x9f, 0xe8, 0xc9, 0xe7, 0x27, 0x82, 0x55, 0x82, 0x55, 0x82,
	0x95, 0x8b, 0xf1, 0xf1, 0xf4, 0xaa, 0x3c, 0x1b, 0xbf, 0x73, 0xd8, 0xfa, 0x8d, 0xbc, 0xae, 0xbe,
	0x13, 0x00, 0xc5, 0xa2, 0x67, 0x1d, 0xba, 0x7c, 0x01, 0x60, 0xdf, 0x8d, 0x23, 0xfb, 0x61, 0x0d,
	0x16, 0xc9, 0x32, 0x59, 0x1f, 0xa9, 0x9d, 0x24, 0xbf, 0x82, 0x19, 0xe9, 0xd0, 0x15, 0x7b, 0xcb,
	0x64, 0x9d, 0xdd, 0x1c, 0x57, 0xe3, 0x46, 0x83, 0x42, 0x31, 0x90, 0xdf, 0x41, 0xd6, 0x7a, 0x17,
	0x08, 0xb5, 0x75, 0x14, 0x8a, 0x7d, 0xe6, 0xcb, 0x09, 0xff, 0xb0, 0x25, 0xd4, 0x2e, 0x9e, 0x5f,
	0xc0, 0x3c, 0x90, 0xa6, 0x3e, 0xbc, 0x7d, 0xf5, 0xa6, 0x37, 0xc5, 0x8c, 0x8b, 0x64, 0x92, 0x3d,
	0x0e, 0xd1, 0x80, 0xa0, 0x09, 0xfd, 0x86, 0x22, 0x72, 0x20, 0x88, 0x64, 0x82, 0x9c, 0x43, 0x66,
	0x10, 0x3d, 0x46, 0x22, 0x95, 0x35, 0x1c, 0x31, 0xb0, 0x7a, 0x85, 0xb9, 0x6c, 0x7f, 0x62, 0xf1,
	0x9f, 0xeb, 0xaf, 0x21, 0x95, 0x0a, 0x71, 0xff, 0xe9, 0x64, 0x8f, 0x68, 0x54, 0x84, 0xb6, 0x7a,
	0xc5, 0xa5, 0xfe, 0xa3, 0x97, 0xfa, 0xbf, 0xe8, 0x45, 0xa3, 0x22, 0x74, 0x7f, 0xf8, 0x92, 0xca,
	0x2f, 0xd0, 0xa4, 0xfc, 0x2d, 0x6f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x16, 0xc6, 0xb2,
	0x48, 0x02, 0x00, 0x00,
}
